<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class EBM_Settings {
	const OPTION = 'ebm_settings';
	public static function defaults() { return array('admin_email'=>get_option('admin_email'),'business_name'=>get_bloginfo('name'),'business_days'=>array('1','2','3','4','5'),'work_start'=>'09:00','work_end'=>'17:00','buffer_minutes'=>15,'max_bookings_per_slot'=>1,'holidays'=>'','global_deposit_type'=>'percent','global_deposit_value'=>25,'stripe_publishable_key'=>'','stripe_secret_key'=>'','stripe_webhook_secret'=>'','google_client_id'=>'','google_client_secret'=>'','google_calendar_id'=>'primary','google_refresh_token'=>'','email_from_name'=>get_bloginfo('name'),'email_from_address'=>get_option('admin_email'),'privacy_page_url'=>get_privacy_policy_url()); }
	public static function all() { $s = get_option(self::OPTION,array()); return wp_parse_args(is_array($s)?$s:array(), self::defaults()); }
	public static function get($key,$default=null){$s=self::all(); return array_key_exists($key,$s)?$s[$key]:$default;}
	public static function secret($key){return EBM_Helpers::decrypt(self::get($key,''));}
	public static function save($raw){$c=self::all(); $c['admin_email']=sanitize_email($raw['admin_email']??$c['admin_email']); $c['business_name']=sanitize_text_field($raw['business_name']??$c['business_name']); $c['work_start']=sanitize_text_field($raw['work_start']??'09:00'); $c['work_end']=sanitize_text_field($raw['work_end']??'17:00'); $c['buffer_minutes']=absint($raw['buffer_minutes']??15); $c['max_bookings_per_slot']=max(1,absint($raw['max_bookings_per_slot']??1)); $c['holidays']=sanitize_textarea_field($raw['holidays']??''); $c['global_deposit_type']=in_array(($raw['global_deposit_type']??'percent'),array('percent','fixed'),true)?sanitize_key($raw['global_deposit_type']):'percent'; $c['global_deposit_value']=(float)($raw['global_deposit_value']??25); $c['stripe_publishable_key']=sanitize_text_field($raw['stripe_publishable_key']??''); $c['google_client_id']=sanitize_text_field($raw['google_client_id']??''); $c['google_calendar_id']=sanitize_text_field($raw['google_calendar_id']??'primary'); $c['email_from_name']=sanitize_text_field($raw['email_from_name']??$c['email_from_name']); $c['email_from_address']=sanitize_email($raw['email_from_address']??$c['email_from_address']); $c['privacy_page_url']=esc_url_raw($raw['privacy_page_url']??''); $days=is_array($raw['business_days']??null)?array_map('sanitize_key',$raw['business_days']):array(); $c['business_days']=array_values(array_intersect($days,array('0','1','2','3','4','5','6'))) ?: array('1','2','3','4','5'); foreach(array('stripe_secret_key','stripe_webhook_secret','google_client_secret') as $k){ if(!empty($raw[$k])){$c[$k]=EBM_Helpers::encrypt(sanitize_text_field($raw[$k]));}} update_option(self::OPTION,$c,false);}
}
