<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class EBM_Scheduler {
	public static function is_business_day(DateTime $d){$days=EBM_Settings::get('business_days',array('1','2','3','4','5')); if(!in_array($d->format('w'),$days,true)){return false;} $holidays=array_filter(array_map('trim',explode("\n",EBM_Settings::get('holidays','')))); return !in_array($d->format('Y-m-d'),$holidays,true);}
	public static function segments($date,$time,$minutes){$out=array();$remain=max(1,absint($minutes));$work_start=EBM_Settings::get('work_start','09:00');$work_end=EBM_Settings::get('work_end','17:00');$d=new DateTime(sanitize_text_field($date));$t=sanitize_text_field($time);while($remain>0&&count($out)<80){if(!self::is_business_day($d)){$d->modify('+1 day');$t=$work_start;continue;}$s=new DateTime($d->format('Y-m-d').' '.$t);$e=new DateTime($d->format('Y-m-d').' '.$work_end);if($s>=$e){$d->modify('+1 day');$t=$work_start;continue;}$available=(int)(($e->getTimestamp()-$s->getTimestamp())/60);$use=min($available,$remain);$end=clone $s;$end->modify('+'.$use.' minutes');$out[]=array('date'=>$d->format('Y-m-d'),'start_at'=>$s->format('Y-m-d H:i:s'),'end_at'=>$end->format('Y-m-d H:i:s'));$remain-=$use;$d->modify('+1 day');$t=$work_start;}return $out;}
	public static function duration($job_id,$addons){global $wpdb;$job=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.EBM_Helpers::table('jobs').' WHERE id=%d AND is_active=1',$job_id)); if(!$job){return 0;} $total=(int)$job->duration_minutes; foreach($addons as $id=>$qty){$a=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.EBM_Helpers::table('addons').' WHERE id=%d AND job_id=%d AND is_active=1',$id,$job_id)); if($a){$q=min(max(absint($qty),(int)$a->min_qty),(int)$a->max_qty);$total+=(int)$a->extra_duration_minutes*$q;}} return $total;}
	public static function price($job_id,$addons){global $wpdb;$job=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.EBM_Helpers::table('jobs').' WHERE id=%d AND is_active=1',$job_id)); if(!$job){return 0;} $total=(float)$job->price; foreach($addons as $id=>$qty){$a=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.EBM_Helpers::table('addons').' WHERE id=%d AND job_id=%d AND is_active=1',$id,$job_id)); if($a){$q=min(max(absint($qty),(int)$a->min_qty),(int)$a->max_qty);$total+=(float)$a->price*$q;}} return round($total,2);}
	public static function deposit($job,$total){$type=($job->deposit_type&&'global'!==$job->deposit_type)?$job->deposit_type:EBM_Settings::get('global_deposit_type','percent');$value=(null!==$job->deposit_value&&''!==$job->deposit_value)?(float)$job->deposit_value:(float)EBM_Settings::get('global_deposit_value',25);$dep=('fixed'===$type)?$value:($total*($value/100)); return round(min(max(0,$dep),$total),2);}
	public static function available($segments,$exclude=0){global $wpdb;$days=EBM_Helpers::table('booking_days');$bookings=EBM_Helpers::table('bookings');$max=(int)EBM_Settings::get('max_bookings_per_slot',1);$buffer=(int)EBM_Settings::get('buffer_minutes',15); foreach($segments as $seg){$start=gmdate('Y-m-d H:i:s',strtotime($seg['start_at'])-$buffer*60);$end=gmdate('Y-m-d H:i:s',strtotime($seg['end_at'])+$buffer*60);$count=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $days d INNER JOIN $bookings b ON b.id=d.booking_id WHERE b.status IN ('pending_payment','confirmed') AND b.id != %d AND d.start_at < %s AND d.end_at > %s",$exclude,$end,$start)); if($count>=$max){return false;}} return !EBM_Google::conflicts($segments);}
	public static function slots($job_id,$date,$addons){$duration=self::duration($job_id,$addons);$out=array();$cursor=new DateTime($date.' '.EBM_Settings::get('work_start','09:00'));$limit=new DateTime($date.' '.EBM_Settings::get('work_end','17:00'));while($cursor<$limit){$time=$cursor->format('H:i');$segs=self::segments($date,$time,$duration);if($segs&&self::available($segs)){$out[]=array('time'=>$time,'segments'=>$segs);} $cursor->modify('+30 minutes');} return $out;}
}
