<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class EBM_DB {
	public static function activate() { self::tables(); self::seed(); if ( ! wp_next_scheduled( 'ebm_send_reminders' ) ) { wp_schedule_event( time() + HOUR_IN_SECONDS, 'hourly', 'ebm_send_reminders' ); } }
	public static function deactivate() { wp_clear_scheduled_hook( 'ebm_send_reminders' ); }
	public static function tables() {
		global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $c = $wpdb->get_charset_collate();
		$sql = array();
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('jobs') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,title VARCHAR(190) NOT NULL,description LONGTEXT NULL,price DECIMAL(10,2) NOT NULL DEFAULT 0,duration_minutes INT UNSIGNED NOT NULL DEFAULT 60,deposit_type VARCHAR(20) NOT NULL DEFAULT 'global',deposit_value DECIMAL(10,2) NULL,allow_split_days TINYINT(1) NOT NULL DEFAULT 1,custom_fields LONGTEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),KEY is_active(is_active)) $c;";
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('addons') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,job_id BIGINT UNSIGNED NOT NULL,title VARCHAR(190) NOT NULL,description LONGTEXT NULL,price DECIMAL(10,2) NOT NULL DEFAULT 0,min_qty INT UNSIGNED NOT NULL DEFAULT 0,max_qty INT UNSIGNED NOT NULL DEFAULT 1,extra_duration_minutes INT UNSIGNED NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),KEY job_id(job_id)) $c;";
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('customers') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(190) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(80) NOT NULL,address LONGTEXT NOT NULL,privacy_accepted_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),KEY email(email)) $c;";
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('bookings') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_token VARCHAR(64) NOT NULL,job_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending_payment',start_at DATETIME NOT NULL,end_at DATETIME NOT NULL,total_minutes INT UNSIGNED NOT NULL,total_amount DECIMAL(10,2) NOT NULL,deposit_amount DECIMAL(10,2) NOT NULL,balance_amount DECIMAL(10,2) NOT NULL,addons_json LONGTEXT NULL,custom_fields_json LONGTEXT NULL,stripe_session_id VARCHAR(190) NULL,google_event_id VARCHAR(190) NULL,reminder_sent TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_token(public_token),KEY status(status),KEY start_at(start_at)) $c;";
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('booking_days') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,booking_id BIGINT UNSIGNED NOT NULL,work_date DATE NOT NULL,start_at DATETIME NOT NULL,end_at DATETIME NOT NULL,PRIMARY KEY(id),KEY booking_id(booking_id),KEY work_date(work_date),KEY times(start_at,end_at)) $c;";
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('transactions') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,booking_id BIGINT UNSIGNED NOT NULL,type VARCHAR(40) NOT NULL,status VARCHAR(40) NOT NULL,amount DECIMAL(10,2) NOT NULL DEFAULT 0,provider VARCHAR(40) NOT NULL DEFAULT 'stripe',provider_id VARCHAR(190) NULL,note LONGTEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),KEY booking_id(booking_id)) $c;";
		$sql[] = "CREATE TABLE " . EBM_Helpers::table('rate_limits') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,ip_hash VARCHAR(64) NOT NULL,action_key VARCHAR(60) NOT NULL,attempts INT UNSIGNED NOT NULL DEFAULT 1,window_start DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY ip_action(ip_hash,action_key)) $c;";
		foreach ( $sql as $q ) { dbDelta( $q ); }
	}
	private static function seed() { global $wpdb; $table = EBM_Helpers::table('jobs'); if ( (int) $wpdb->get_var("SELECT COUNT(*) FROM $table") ) { return; } $now = current_time('mysql'); $wpdb->insert($table,array('title'=>'Install new light fitting','description'=>'Choose a date for a qualified electrician to install a new light fitting.','price'=>95,'duration_minutes'=>90,'created_at'=>$now,'updated_at'=>$now),array('%s','%s','%f','%d','%s','%s')); }
	public static function rate_limited( $action, $limit = 8, $minutes = 15 ) { global $wpdb; $ip = sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ?? 'unknown' ) ); $hash = hash_hmac('sha256',$ip,wp_salt('nonce')); $t = EBM_Helpers::table('rate_limits'); $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE ip_hash=%s AND action_key=%s",$hash,$action)); $now = current_time('mysql'); if(!$row){$wpdb->insert($t,array('ip_hash'=>$hash,'action_key'=>$action,'attempts'=>1,'window_start'=>$now),array('%s','%s','%d','%s'));return false;} if(time()-strtotime($row->window_start)>$minutes*MINUTE_IN_SECONDS){$wpdb->update($t,array('attempts'=>1,'window_start'=>$now),array('id'=>(int)$row->id),array('%d','%s'),array('%d'));return false;} if((int)$row->attempts >= $limit){return true;} $wpdb->query($wpdb->prepare("UPDATE $t SET attempts=attempts+1 WHERE id=%d",(int)$row->id)); return false; }
}
