<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class EBM_Emails {
	private static function headers(){return array('Content-Type: text/html; charset=UTF-8','From: '.sanitize_text_field(EBM_Settings::get('email_from_name',get_bloginfo('name'))).' <'.sanitize_email(EBM_Settings::get('email_from_address',get_option('admin_email'))).'>');}
	private static function booking($id){global $wpdb;return $wpdb->get_row($wpdb->prepare('SELECT b.*,j.title job_title,c.name,c.email,c.phone,c.address FROM '.EBM_Helpers::table('bookings').' b INNER JOIN '.EBM_Helpers::table('jobs').' j ON j.id=b.job_id INNER JOIN '.EBM_Helpers::table('customers').' c ON c.id=b.customer_id WHERE b.id=%d',$id));}
	private static function wrap($title,$html){return '<div style="font-family:Arial,sans-serif;line-height:1.5;color:#111827;max-width:680px;margin:auto;padding:24px;border:1px solid #e5e7eb;border-radius:12px"><h1 style="font-size:24px;margin-top:0">'.esc_html($title).'</h1>'.wp_kses_post($html).'</div>';}
	public static function confirmation($id){$b=self::booking($id); if(!$b){return false;} $content='<p>Your booking has been confirmed.</p><p><strong>Service:</strong> '.esc_html($b->job_title).'<br><strong>Schedule:</strong> '.esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$b->start_at)).' to '.esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$b->end_at)).'<br><strong>Address:</strong> '.nl2br(esc_html($b->address)).'<br><strong>Total:</strong> '.esc_html(EBM_Helpers::money($b->total_amount)).'<br><strong>Deposit paid:</strong> '.esc_html(EBM_Helpers::money($b->deposit_amount)).'<br><strong>Balance:</strong> '.esc_html(EBM_Helpers::money($b->balance_amount)).'</p>'; wp_mail($b->email,__('Booking confirmation','electrical-booking-manager'),self::wrap(__('Booking confirmation','electrical-booking-manager'),$content),self::headers()); $admin='<p>A new booking has been received.</p><p><strong>Customer:</strong> '.esc_html($b->name).'<br><strong>Email:</strong> '.esc_html($b->email).'<br><strong>Phone:</strong> '.esc_html($b->phone).'<br><strong>Service:</strong> '.esc_html($b->job_title).'</p>'; return wp_mail(EBM_Settings::get('admin_email',get_option('admin_email')),__('New booking received','electrical-booking-manager'),self::wrap(__('New booking received','electrical-booking-manager'),$admin),self::headers());}
	public static function send_due_reminders(){global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT id FROM '.EBM_Helpers::table('bookings')." WHERE status='confirmed' AND reminder_sent=0 AND start_at BETWEEN %s AND %s",current_time('mysql'),gmdate('Y-m-d H:i:s',current_time('timestamp')+DAY_IN_SECONDS+HOUR_IN_SECONDS))); foreach($rows as $r){self::reminder((int)$r->id);}}
	public static function reminder($id){global $wpdb;$b=self::booking($id); if(!$b){return false;} $sent=wp_mail($b->email,__('Booking reminder','electrical-booking-manager'),self::wrap(__('Booking reminder','electrical-booking-manager'),'<p>Your booking starts at '.esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$b->start_at)).'.</p>'),self::headers()); if($sent){$wpdb->update(EBM_Helpers::table('bookings'),array('reminder_sent'=>1),array('id'=>$id),array('%d'),array('%d'));} return $sent;}
	public static function balance($id,$url){$b=self::booking($id); if(!$b){return false;} return wp_mail($b->email,__('Remaining balance payment','electrical-booking-manager'),self::wrap(__('Remaining balance payment','electrical-booking-manager'),'<p>Please pay the remaining balance: <strong>'.esc_html(EBM_Helpers::money($b->balance_amount)).'</strong></p><p><a href="'.esc_url($url).'">Pay balance</a></p>'),self::headers());}
}
